#!/bin/bash
# $1 = query string sent by form.
# e.g. "job=bayes&min=20&max=30"

# Tweet => Text
# RedditPost => Text
# Text => Sentiment

# label is the channel
# heartbeat packet has the fsm state can be status (as a baby step)

# random_number > fifo
# ( echo heartbeat_packet; cat fifo ) | jq . -s

# nectar> create job random 20 30
# 
nectar-create-job(){
  job=$1
  cat <<EOF
1. find nectardb dir
2. check if nectardb/jobs/$job
3. create nectardb/jobs/job/{fifo,update}
4. create nectar/channels/?job=$job&
EOF

  create_fn="nectar-create-job-$1"
  $create_fn "${@:1}"
  #"${!create_fn}"
}

nectar-create-job-random(){
  echo "IN NECTAR-CREATE_JOM_RANDOM with ${@}"
}

 
make-heartbeat-array(){
  cat "./lockdown.json"
}

make-heartbeat-array 
