#!/bin/bash
db="/home/admin/src/live-topic-analysis/investigations/sparkline/nectardb"
job="bayes"
qs="$(basename $PWD)" #"min=15&max=58"
# parse query string here so per-channel data can be 
# used in the business logic (e.g. shuffle).

function parse-query(){
    saveIFS=$IFS
    IFS='=&'
    parm=($1)
    IFS=$saveIFS
    echo "${parm[@]}"
}

qsarray=( $(parse-query "$qs") )

low=${1:-"${qsarray[1]}"}
high=${2:-"${qsarray[3]}"}

channel="$job/$qs"
cat <<EOF
{
    "id": "$(date +%s%N)",
    "type": "data.random",
    "channel": "$channel",
    "data": "$(shuf -i $low-$high -n 1)"
}
EOF
