#!/bin/bash

# This is a server side dispatcher 
# that dispatches to nectardb channels by 
# calling $db/$channel/update.
# By Convention, channel update writes to 
# $db/$channel/fifo.

db="/home/admin/src/live-topic-analysis/investigations/sparkline/nectardb"
job="bayes"
querystrings=("min=15&max=52", "min=18&max=58")
low=${1:-0}
high=${2:-20}
parentIds=(001 002)
index=0;

function parse-query(){
    saveIFS=$IFS
    IFS='=&'
    parm=($1)
    IFS=$saveIFS
    echo "$parm"
}

for query in "${querystrings[@]}"
do
#echo "$(parse-query query)"
cat <<EOF
{
    "id": "$(date +%s%N)",
    "type": "data.random",
    "parent": "${parentIds[$index]}",
    "channel": "$job/$query",
    "data": "$(shuf -i $low-$high -n 1)"
}
EOF

(( index++ ))

done | jq -s

